name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test step"

  integration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an integration step"
      - run: exit 1

  prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a deploy step"
