name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab


  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "This is a test step"

  artifact:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "This is a artifact step"> output.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-output
          path: output.txt

  integration:
    runs-on: ubuntu-latest
    needs: [artifact]
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - run: echo "This is a deploy step"

